### ISSUE TITLE
needs info 

### ISSUE THREAD

**Issue by tomahawk666** [saravanan-k90/python-jedi#16]
Hey guys,

just wanna know if you're are planning any update for this awesome plugin?

best regards

**Comment by saravanan-k90** [comment]
Hey i do not know whether you are a fake - by account. 
Anyways answer for your question,

In my current locality where people outside listen or record to what i speak inside my house and they loop around with what i spoke without my knowledge and they dwell around and trying to bury me into a trench which i am not knowing. At-least i know i am not a part of anything they are digging or dwelling or looping that i am most cared about.
For these crimes they are doing around me.. i am trying to keep myself out of whatever they are trying to make me into to laugh at me.

I also don't have a good system.

These are the reasons for why i am not currently maintaining this plugin. 
When i get money to get a good system and switch to a better locality i may at-least think of maintaining this code or at-least update it as out of maintenance.

**Comment by saravanan-k90** [comment]
The reason i have stated is true to the best of my soulful knowledge.
