### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Thor77** [saravanan-k90/python-jedi#2]
Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.
```
Object.Object.defineProperty.get (/usr/share/atom/resources/app/exports/atom.js:43:9)
Object.<anonymous> (/home/jonas/.atom/packages/python-jedi/lib/jedi-python3-provider.coffee:1:1)
```

**Comment by saravanan-k90** [comment]
Fixed Deprecated calls in v0.1.8. Thanks and I really appreciate @Thor77.
