### ISSUE TITLE
python-jedi should rather/also use activate script

### ISSUE THREAD

**Issue by mfalesni** [saravanan-k90/python-jedi#5]
In the project I am working on, we add some directories in PYTHONPATH in the activate script in the virtualenv. Since python-jedi uses just the python executable, it does not see the directories added in the PYTHONPATH and therefore does not offer the autocompletion for them.

**Comment by saravanan-k90** [comment]
@mfalesni  i am sorry, i didn't really do deep check over that part(that's my knowledge level in python. sorry for that). If you can solve it., it will be helpful.

**Comment by mfalesni** [comment]
@saravanan-k90 Thanks for answer. Unfortunately I have no experience with developing plugins for Atom, nor obscure languages like CoffeeScript. The activate usage would be very simple, instead of calling `<virtualenv_path>/bin/python autocompleteserver.py`, you would do two calls in the shell, like this: `<virtualenv_path>/bin/activate; python autocompleteserver.py`. That is the supposed way to do it with virtualenv because it sets all things as supposed. If the child_process does not support executing full bash shell commands, then you would use it like this: `bash -c "<virtualenv_path>/bin/activate; python autocompleteserver.py"`. This should work on the all sane operating systems, not sure of Windows though ...

**Comment by saravanan-k90** [comment]
I don't think python-jedi work well with windows. 

The part you're idea - " first put a command out to activate  and then call autocompleteserver.py"
I'll try it out this week or the next week. 

If any errors on that possible try, i will comment you about that.

**Comment by saravanan-k90** [comment]
I didn't try any changes yet, but what i feel is, i don't want to activate it using python-jedi(temporarily). No activation but enabling possible completions from virtualenv. For packages installed using pip it does show completions but for added , do jedi module brings auto completions for added directories(clear my doubt).
