### ISSUE TITLE
Is goto-definition possible?

### ISSUE THREAD

**Issue by mbrochh** [saravanan-k90/python-jedi#6]
The plugin seems to work great, even recognizes the currently active venv.

I'm wondering if it is possible to jump to definition somehow? I can do that with jedi-vim and it's sooooooo useful :)

**Comment by saravanan-k90** [comment]
Sorry @mbrochh i know about this only now., i will check that....

**Comment by saravanan-k90** [comment]
I checked jedi api for goto definition,

Please correct me if i am wrong,

goto definition - shows the typed word as already defined(i.e., <Definition def demo>)  inside auto complete popup -> pressing tab or enter should take the cursor to the defined statement, function or class.

**Comment by mbrochh** [comment]
Yep! Basically I can write "from django.db import models" and then place
the cursor on "models" and press the shortcut for "goto definition" and it
will open the file where "models" is defined in a new tab

**Comment by saravanan-k90** [comment]
In version 0.3.2., I used goto_definitions and key-mapped the functionality to ctrl-alt-j
